version: '3.9'
services:
  bot:
    build:
      context: ./
      dockerfile: ./Dockerfile.dev
    depends_on:
      - database
    volumes:
      - ./:/app
  database:
    image: postgres:13.2-alpine
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
  phppgadmin:
    image: bitnami/phppgadmin:7
    environment:
      DATABASE_HOST: database
      DATABASE_PORT_NUMBER: ${POSTGRES_PORT}
    ports:
      - '8080:8080'
    depends_on:
      - database
volumes:
  postgres-data:
